// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title MockYieldProvider
 * @dev Simulates a DeFi protocol (like Aave or Lido) where the principal is deposited
 * to earn yield. For demo purposes, the yield amount is manually set by the deployer
 * or the contract owner when settling the pool.
 */
contract MockYieldProvider {
    address public owner;
    mapping(address => bool) public authorizedPools;
    mapping(address => uint256) public poolYields;

    event PrincipalDeposited(address indexed poolAddress, uint256 amount);
    event YieldSet(address indexed poolAddress, uint256 yieldAmount);
    event PrincipalAndYieldReturned(address indexed poolAddress, uint256 totalReturn);

    constructor() {
        owner = msg.sender;
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner can call");
        _;
    }

    modifier onlyOwnerOrPool() {
        require(msg.sender == owner || authorizedPools[msg.sender], "Only owner or authorized pool can call");
        _;
    }

    /**
     * @dev Authorize a pool contract to call yield functions
     */
    function authorizePool(address _poolAddress) external onlyOwner {
        authorizedPools[_poolAddress] = true;
    }

    /**
     * @dev Simulates the action of sending the pool's principal to a DeFi protocol.
     * @param _poolAddress The address of the betting pool contract.
     * @param _amount The principal amount (Sponsor + Participants deposits).
     */
    function depositPrincipal(address _poolAddress, uint256 _amount) public payable {
        require(msg.value == _amount, "Deposit amount mismatch");
        emit PrincipalDeposited(_poolAddress, _amount);
        // Funds are held in this contract's balance
    }

    /**
     * @dev Sets the simulated yield generated by the principal (called by the owner or pool).
     */
    function setPoolYield(address _poolAddress, uint256 _yieldAmount) public onlyOwnerOrPool {
        poolYields[_poolAddress] = _yieldAmount;
        emit YieldSet(_poolAddress, _yieldAmount);
    }

    /**
     * @dev Returns the total funds (Principal + Yield) back to the Pool for distribution.
     * @param _poolAddress The address of the betting pool contract.
     * @param _totalAmount The total principal + yield to be returned.
     */
    function returnPrincipalAndYield(address _poolAddress, uint256 _totalAmount) public onlyOwnerOrPool {
        // Conceptually transfers funds from the DeFi protocol back to the pool
        (bool success, ) = payable(_poolAddress).call{value: _totalAmount}("");
        require(success, "Transfer failed");

        // Clear the yield record
        delete poolYields[_poolAddress];

        emit PrincipalAndYieldReturned(_poolAddress, _totalAmount);
    }
}

